Add example to `Token!` documentation
dtolnay/syn pull request #1510
Opened 2023-09-14 09:41 UTC by ModProg

This allows rust-analyzer to correctly complete the preferred brackets, instead of parenthesis.

https://github.com/rust-lang/rust-analyzer/issues/15608#issuecomment-1718821707

I wasn't sure what to put in there as the extensive documentation is ad the module doc

2023-09-14 10:14 UTC, ModProg commented on src/token.rs
> +/// ```
```suggestion
/// ```
/// # syn::Token;
```

2023-09-14 10:22 UTC, ModProg commented on src/token.rs
> +/// # syn::Token;
```suggestion
/// # use syn::Token;
```

2023-09-14 10:32 UTC, ModProg commented on src/token.rs
> +/// Token![>>]; // syn::token::Shr
```suggestion
/// # type a =
/// Token![fn]; // syn::token::Fn
/// # type b =
/// Token![>>]; // syn::token::Shr
```

2023-09-15 19:05 UTC, dtolnay requested changes
Thanks for the PR!

The example you wrote would get shown to the reader like this:

<img src="https://github.com/dtolnay/syn/assets/1940490/f34b03ba-3398-4e14-9560-f1dd9c2c26f8" width="500">

which is pretty misleading as to how this macro is supposed to be used.

```console
error: macro expansion ends with an incomplete expression: expected one of `!` or `::`
   --> syn-2.0.31/src/token.rs:866:41
    |
866 |     [fn]          => { $crate::token::Fn };
    |                                         ^ expected one of `!` or `::`
    |
   ::: src/lib.rs:1:1
    |
1   | Token![fn]; // syn::token::Fn
    | ---------- in this macro invocation
```

Could you come up with a more meaningful usage to show in the example?

2023-09-15 21:33 UTC, dtolnay approved these changes

2023-09-15 21:33 UTC, merged